

spring:
  
  datasource: 
     url: jdbc:postgresql://localhost:5432/postgres
     username: psql1
     password: psql1
  batch:
     initialize-schema: always   
       
   

  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          enable_lazy_load_no_trans: true
