server:
  port: 8087

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vamshi57/config-server/blob/main/application.yml
          clone-on-start: true
          
          